### ISSUE TITLE
OPTscat Header

### ISSUE THREAD

**Issue by real-guilty** [nm004/ngs2-nm-plugin#1]
Is it only the presence of the OPTscat headers under NodeObj that dictate whether the crush effects will function correctly? For instance, the ninja dogs (e_okm_a and e_okm_b) each have OPTscat. I haven't tested it myself, but theoretically, would this mean they would have crush effects? 

If true, maybe we can investigate how to integrate preexisting mesh objects and header info into the assets where such things are missing.

**Comment by nm004** [comment]
I think OPTscat and its related data are not in the NodeObj section only, but also are in other sections too. 

Dogs have OPTscat since, in NG2, the crush effects happen when they get hit. I could see the blood trail in some NG2 videos.

**Comment by real-guilty** [comment]
Indeed, there are OPTscat headers under ObjGeo too. I copied the OPTscat bytes from the mage TMC to the e_nin_a TMC, adjusted the memory size bytes, and copied the crush parts from the mage’s mesh to e_nin_a in Blender hoping I could convert the FBX to a functioning TMC with that data included, but unsurprisingly, that failed. Could that even work? I don’t know exactly what is read, but could any of the existing OPTscat data be copied to another TMC and actually read?

**Comment by nm004** [comment]
At least "MdlInfo", "HieLay", "NodeLay", "GlblMtx" and "BnOfsMtx" seems to be related as they have the same number of items. Also, some unnamed sections need to be adjusted because they are read when doing crush effect stuff.

**Comment by real-guilty** [comment]
I have Sigma 2+ TMC files pulled from my Vita, and FiendBusa stated TMCs could be pulled from memory with the Vita emulator running, so we're wondering if it would be easier to transplant corresponding S2+ TMC data rather than cannibalize from the same few S2 Master Collection files.

As an aside, let me know if you want to take this discussion to Discord or elsewhere.

**Comment by nm004** [comment]
[Gib injector](https://github.com/nm004/ngs2-gibinjector) solved this issue.
